import csv, random
from datetime import datetime, timedelta

def random_data():
    order_id = random.randint(1000, 9999)
    customer_id = random.randint(100, 999)
    order_date = (datetime.now() - timedelta(days=random.randint(1, 365))).strftime('%d-%m-%y')
    product_id = random.randint(1, 100)
    product_name = f"Product{product_id}"
    product_price = round(random.uniform(10, 1000), 2)
    quantity = random.randint(1, 10)

    return [order_id, customer_id, order_date, product_id, product_name, product_price, quantity]



def writer_csv():
    data_length = 10
    with open('orders.csv','w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['Order_ID', 'Customer_ID', 'Order_Date', 'Product_ID', 'Product_Name', 'Product_Price', 'Quantity'])
        for _ in range(data_length):
            writer.writerow(random_data())

def revenue_generated_in_each_month():
    revenue = {}

    with open('orders.csv','r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            order_date = datetime.strptime(row['Order_Date'], '%d-%m-%y')
            month = order_date.month
            rev = round(float(row['Product_Price']),2) * int(row['Quantity'])
            if month in revenue:
                revenue[month] += rev
            else:
                revenue[month] = rev

        for k,v in revenue.items():
            print(f"Month: {k}, Total Revenue generated in each month: {v}")

def revenue_generated_by_each_product():
    revenue = {}
    with open('orders.csv','r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            product_name = row['Product_Name']
            rev = round(float(row['Product_Price']),2) * int(row['Quantity'])
            if product_name in revenue:
                revenue[product_name] += rev
            else:
                revenue[product_name] = rev

    for k,v in revenue.items():
        print(f"Product Name: {k}, Total Revenue generated by product: {v}")
